// ignore_for_file: prefer_const_constructors

import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../database/models/decision_record.dart';
import '../domain/models/analysis_result.dart';

class PdfService {
  int _monthlyExportCount = 0;

  bool get canExport => true;
  int get remainingExports => 999;
  int get monthlyExportCount => _monthlyExportCount;

  void _incrementExportCount() {
    _monthlyExportCount++;
  }

  Future<Uint8List> generateAnalysisPdf({
    required AnalysisResult result,
    required DecisionRecord record,
  }) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(56),
        header: (context) => pw.Container(
          alignment: pw.Alignment.centerRight,
          margin: const pw.EdgeInsets.only(bottom: 8),
          child: pw.Text(
            'DecisionAI',
            style: pw.TextStyle(
              fontSize: 9,
              color: PdfColors.grey400,
              letterSpacing: 1.2,
            ),
          ),
        ),
        footer: (context) => pw.Container(
          alignment: pw.Alignment.center,
          margin: const pw.EdgeInsets.only(top: 8),
          child: pw.Column(
            children: <pw.Widget>[
              pw.Divider(height: 1, color: PdfColors.grey300),
              pw.SizedBox(height: 6),
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: <pw.Widget>[
                  pw.Text(
                    'Generated by DecisionAI',
                    style: const pw.TextStyle(
                      fontSize: 8,
                      color: PdfColors.grey400,
                    ),
                  ),
                  pw.Text(
                    'Page ${context.pageNumber}',
                    style: const pw.TextStyle(
                      fontSize: 8,
                      color: PdfColors.grey400,
                    ),
                  ),
                ],
              ),
            ],
          ),
        ),
        build: (context) => <pw.Widget>[
          _buildCoverPage(result),
          pw.SizedBox(height: 32),
          _buildSection('Executive Summary', result.summary),
          pw.SizedBox(height: 24),
          _buildConfidenceSection(result.confidenceScore),
          pw.SizedBox(height: 24),
          _buildSection('Recommendation', result.recommendation),
          if (result.bestChoice != null && result.bestChoice!.isNotEmpty) ...[
            pw.SizedBox(height: 24),
            _buildSection('Best Choice', result.bestChoice!),
          ],
          pw.SizedBox(height: 24),
          _buildProsConsSection(result.pros, result.cons),
          if (result.risks.isNotEmpty) ...[
            pw.SizedBox(height: 24),
            _buildRisksSection(result.risks),
          ],
          if (result.reasoning != null && result.reasoning!.isNotEmpty) ...[
            pw.SizedBox(height: 24),
            _buildSection('Analysis Reasoning', result.reasoning!),
          ],
        ],
      ),
    );

    _incrementExportCount();
    return pdf.save();
  }

  pw.Widget _buildCoverPage(AnalysisResult result) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: <pw.Widget>[
        pw.SizedBox(height: 60),
        pw.Container(
          padding: const pw.EdgeInsets.symmetric(horizontal: 4, vertical: 8),
          decoration: pw.BoxDecoration(
            border: pw.Border(
              left: pw.BorderSide(color: PdfColors.blue700, width: 3),
            ),
          ),
          child: pw.Text(
            'DECISION ANALYSIS',
            style: pw.TextStyle(
              fontSize: 11,
              color: PdfColors.blue700,
              letterSpacing: 3,
              fontWeight: pw.FontWeight.bold,
            ),
          ),
        ),
        pw.SizedBox(height: 16),
        pw.Text(
          result.decisionTitle,
          style: const pw.TextStyle(
            fontSize: 28,
            fontWeight: pw.FontWeight.bold,
            color: PdfColors.grey900,
          ),
        ),
        pw.SizedBox(height: 24),
        pw.Container(
          padding: const pw.EdgeInsets.all(16),
          decoration: const pw.BoxDecoration(
            color: PdfColors.grey100,
            borderRadius: pw.BorderRadius.all(pw.Radius.circular(8)),
          ),
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: <pw.Widget>[
              _infoRow('Date', _formatDate(result.analyzedAt)),
              pw.SizedBox(height: 8),
              _infoRow('AI Model', result.usedModel),
              pw.SizedBox(height: 8),
              _infoRow(
                'Confidence',
                '${(result.confidenceScore * 100).round()}%',
              ),
            ],
          ),
        ),
        pw.SizedBox(height: 40),
        pw.Divider(height: 1, color: PdfColors.grey300),
      ],
    );
  }

  pw.Widget _infoRow(String label, String value) {
    return pw.Row(
      children: <pw.Widget>[
        pw.SizedBox(
          width: 100,
          child: pw.Text(
            label,
            style: const pw.TextStyle(
              fontSize: 10,
              color: PdfColors.grey500,
            ),
          ),
        ),
        pw.Text(
          value,
          style: const pw.TextStyle(
            fontSize: 11,
            color: PdfColors.grey800,
          ),
        ),
      ],
    );
  }

  pw.Widget _buildSection(String title, String content) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: <pw.Widget>[
        pw.Row(
          children: <pw.Widget>[
            pw.Container(
              width: 4,
              height: 18,
              decoration: const pw.BoxDecoration(
                color: PdfColors.blue700,
                borderRadius: pw.BorderRadius.all(pw.Radius.circular(2)),
              ),
            ),
            pw.SizedBox(width: 10),
            pw.Text(
              title,
              style: const pw.TextStyle(
                fontSize: 16,
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.grey800,
              ),
            ),
          ],
        ),
        pw.SizedBox(height: 12),
        pw.Container(
          padding: const pw.EdgeInsets.all(16),
          decoration: const pw.BoxDecoration(
            color: PdfColors.grey100,
            borderRadius: pw.BorderRadius.all(pw.Radius.circular(8)),
            border: pw.Border(
              top: pw.BorderSide(color: PdfColors.grey300),
              right: pw.BorderSide(color: PdfColors.grey300),
              bottom: pw.BorderSide(color: PdfColors.grey300),
              left: pw.BorderSide(color: PdfColors.grey300),
            ),
          ),
          child: pw.Text(
            content,
            style: const pw.TextStyle(
              fontSize: 10.5,
              color: PdfColors.grey700,
            ),
          ),
        ),
      ],
    );
  }

  pw.Widget _buildConfidenceSection(double score) {
    final percent = (score * 100).round();
    final color = percent >= 80
        ? PdfColors.green700
        : percent >= 60
            ? PdfColors.orange700
            : PdfColors.red700;

    final bgColor = percent >= 80
        ? PdfColors.green100
        : percent >= 60
            ? PdfColors.orange100
            : PdfColors.red100;

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: <pw.Widget>[
        pw.Row(
          children: <pw.Widget>[
            pw.Container(
              width: 4,
              height: 18,
              decoration: const pw.BoxDecoration(
                color: PdfColors.blue700,
                borderRadius: pw.BorderRadius.all(pw.Radius.circular(2)),
              ),
            ),
            pw.SizedBox(width: 10),
            pw.Text(
              'Confidence Score',
              style: const pw.TextStyle(
                fontSize: 16,
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.grey800,
              ),
            ),
          ],
        ),
        pw.SizedBox(height: 12),
        pw.Container(
          padding: const pw.EdgeInsets.all(16),
          decoration: pw.BoxDecoration(
            color: bgColor,
            borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
            border: pw.Border(
              top: pw.BorderSide(color: color),
              right: pw.BorderSide(color: color),
              bottom: pw.BorderSide(color: color),
              left: pw.BorderSide(color: color),
            ),
          ),
          child: pw.Column(
            children: <pw.Widget>[
              pw.Container(
                width: 80,
                height: 80,
                decoration: pw.BoxDecoration(
                  color: PdfColors.white,
                  shape: pw.BoxShape.circle,
                ),
                child: pw.Center(
                  child: pw.Text(
                    '$percent%',
                    style: pw.TextStyle(
                      fontSize: 22,
                      fontWeight: pw.FontWeight.bold,
                      color: color,
                    ),
                  ),
                ),
              ),
              pw.SizedBox(height: 8),
              pw.Text(
                _confidenceLabel(percent),
                style: const pw.TextStyle(
                  fontSize: 10,
                  color: PdfColors.grey500,
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }

  pw.Widget _buildProsConsSection(List<String> pros, List<String> cons) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: <pw.Widget>[
        pw.Row(
          children: <pw.Widget>[
            pw.Container(
              width: 4,
              height: 18,
              decoration: const pw.BoxDecoration(
                color: PdfColors.blue700,
                borderRadius: pw.BorderRadius.all(pw.Radius.circular(2)),
              ),
            ),
            pw.SizedBox(width: 10),
            pw.Text(
              'Pros & Cons Analysis',
              style: const pw.TextStyle(
                fontSize: 16,
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.grey800,
              ),
            ),
          ],
        ),
        pw.SizedBox(height: 12),
        pw.Row(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: <pw.Widget>[
            pw.Expanded(
              child: _buildListCard('Pros', pros, PdfColors.green700, PdfColors.green100),
            ),
            pw.SizedBox(width: 12),
            pw.Expanded(
              child: _buildListCard('Cons', cons, PdfColors.red700, PdfColors.red100),
            ),
          ],
        ),
      ],
    );
  }

  pw.Widget _buildListCard(
    String title,
    List<String> items,
    PdfColor accentColor,
    PdfColor bgColor,
  ) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(14),
      decoration: pw.BoxDecoration(
        color: bgColor,
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
        border: pw.Border(
          top: pw.BorderSide(color: accentColor),
          right: pw.BorderSide(color: accentColor),
          bottom: pw.BorderSide(color: accentColor),
          left: pw.BorderSide(color: accentColor),
        ),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: <pw.Widget>[
          pw.Container(
            padding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 3),
            decoration: pw.BoxDecoration(
              color: PdfColors.white,
              borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
            ),
            child: pw.Text(
              title,
              style: pw.TextStyle(
                fontSize: 12,
                fontWeight: pw.FontWeight.bold,
                color: accentColor,
              ),
            ),
          ),
          pw.SizedBox(height: 10),
          ...items.map(
            (item) => pw.Padding(
              padding: const pw.EdgeInsets.only(bottom: 6),
              child: pw.Row(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: <pw.Widget>[
                  pw.Text(
                    '\u2022  ',
                    style: pw.TextStyle(
                      fontSize: 10,
                      color: accentColor,
                    ),
                  ),
                  pw.Expanded(
                    child: pw.Text(
                      item,
                      style: const pw.TextStyle(
                        fontSize: 9.5,
                        color: PdfColors.grey700,
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }

  pw.Widget _buildRisksSection(List<String> risks) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: <pw.Widget>[
        pw.Row(
          children: <pw.Widget>[
            pw.Container(
              width: 4,
              height: 18,
              decoration: const pw.BoxDecoration(
                color: PdfColors.blue700,
                borderRadius: pw.BorderRadius.all(pw.Radius.circular(2)),
              ),
            ),
            pw.SizedBox(width: 10),
            pw.Text(
              'Risks to Consider',
              style: const pw.TextStyle(
                fontSize: 16,
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.grey800,
              ),
            ),
          ],
        ),
        pw.SizedBox(height: 12),
        ...risks.map(
          (risk) => pw.Container(
            margin: const pw.EdgeInsets.only(bottom: 8),
            padding: const pw.EdgeInsets.all(12),
            decoration: const pw.BoxDecoration(
              color: PdfColors.orange100,
              borderRadius: pw.BorderRadius.all(pw.Radius.circular(8)),
              border: pw.Border(
                top: pw.BorderSide(color: PdfColors.orange300),
                right: pw.BorderSide(color: PdfColors.orange300),
                bottom: pw.BorderSide(color: PdfColors.orange300),
                left: pw.BorderSide(color: PdfColors.orange300),
              ),
            ),
            child: pw.Row(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: <pw.Widget>[
                pw.Container(
                  margin: const pw.EdgeInsets.only(top: 1),
                  width: 6,
                  height: 6,
                  decoration: pw.BoxDecoration(
                    color: PdfColors.orange700,
                    shape: pw.BoxShape.circle,
                  ),
                ),
                pw.SizedBox(width: 10),
                pw.Expanded(
                  child: pw.Text(
                    risk,
                    style: const pw.TextStyle(
                      fontSize: 10,
                      color: PdfColors.grey700,
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),
      ],
    );
  }

  String _confidenceLabel(int percent) {
    if (percent >= 90) return 'Very High Confidence';
    if (percent >= 80) return 'High Confidence';
    if (percent >= 60) return 'Moderate Confidence';
    if (percent >= 40) return 'Low Confidence';
    return 'Very Low Confidence';
  }

  String _formatDate(DateTime dt) {
    final months = [
      'January', 'February', 'March', 'April', 'May', 'June',
      'July', 'August', 'September', 'October', 'November', 'December',
    ];
    return '${months[dt.month - 1]} ${dt.day}, ${dt.year}';
  }
}
